title: TechReview Zero
description: Hardware benchmarks, comparisons, and dedicated reviews.
theme: minima
plugins:
  - jekyll-feed

# Navigation Settings
header_pages:
  - index.md
  - about.md
css: /assets/css/custom.css
